#pragma once

#define FORCE_NKRO

#define BOOTMAGIC_LITE_ROW 5
#define BOOTMAGIC_LITE_COLUMN 0

#define RGB_DI_PIN F4
#define DRIVER_LED_TOTAL 10 
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
